name: Batch check (weekdays 7:00 America/Denver)

on:
  workflow_dispatch: {}
  schedule:
    # Fire at both 13:00Z and 14:00Z; a guard only runs when local==07
    - cron: '0 13 * * 1-5'
    - cron: '0 14 * * 1-5'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Guard: only proceed when it's 07 local in Denver
        id: guard
        run: |
          LOCAL_HOUR=$(TZ=America/Denver date +%H)
          echo "Local hour: $LOCAL_HOUR"
          if [ "$LOCAL_HOUR" != "07" ]; then
            echo "Not 07 in America/Denver; exiting."
            exit 78  # neutral (skipped)
          fi

      - name: Call batch-check and post to Slack
        if: ${{ success() }}
        env:
          API_URL: ${{ secrets.RDB_API_URL }}          # e.g., https://your-host
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}  # Slack Incoming Webhook
        run: |
          set -e
          RES=$(curl -s "$API_URL/batch-check")
          UPDATED=$(echo "$RES" | jq '[.results[] | select(.updated==true)] | length')
          TEXT="Regulatory update check: *${UPDATED}* site(s) changed."
          curl -s -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"${TEXT}\"}" \
            "$SLACK_WEBHOOK"
